export const EVENT_TYPE = Object.freeze({
  TARGET_SPAWNED: 'TARGET_SPAWNED',
  THREAT_ALERT: 'THREAT_ALERT',
  TRACK_DETECTED: 'TRACK_DETECTED',
  TRACK_ESTABLISHED: 'TRACK_ESTABLISHED',
  TRACK_SOURCE_HANDOFF: 'TRACK_SOURCE_HANDOFF',
  SEEKER_SEARCH: 'SEEKER_SEARCH',
  SEEKER_ACQUIRED: 'SEEKER_ACQUIRED',
  SEEKER_LOST: 'SEEKER_LOST',
  SEEKER_REACQUIRED: 'SEEKER_REACQUIRED',
  INTERCEPTOR_LAUNCHED: 'INTERCEPTOR_LAUNCHED',
  AUTO_TARGET_ASSIGNED: 'AUTO_TARGET_ASSIGNED',
  AUTO_ENGAGEMENT: 'AUTO_ENGAGEMENT',
  INTERCEPTOR_QUEUED: 'INTERCEPTOR_QUEUED',
  ENGAGEMENT_CANCELLED: 'ENGAGEMENT_CANCELLED',
  NO_AMMO: 'NO_AMMO',
  INTERCEPTOR_FAILED: 'INTERCEPTOR_FAILED',
  INTERCEPTOR_SELF_DESTRUCT: 'INTERCEPTOR_SELF_DESTRUCT',
  TARGET_INTERCEPTED: 'TARGET_INTERCEPTED',
  GUN_BURST_STARTED: 'GUN_BURST_STARTED',
  GUN_BURST_RESOLVED: 'GUN_BURST_RESOLVED',
  TARGET_ESCAPED: 'TARGET_ESCAPED',
  CONTROLLABLE_LAUNCHED: 'CONTROLLABLE_LAUNCHED',
  CONTROLLABLE_HIT: 'CONTROLLABLE_HIT',
  CONTROLLABLE_CRASHED: 'CONTROLLABLE_CRASHED',
});

export function createSimulationEvent(sequence, type, simulationTime, details = {}) {
  return {
    id: `EVT-${sequence.toString().padStart(4, '0')}`,
    type,
    simulationTime,
    details,
  };
}
